wrk.method="GET"
wrk.headers["Content-Type"] = "application/json"
wrk.headers["User-Agent"] = "PostmanRuntime/7.32.3"
-- 记得修改这个，你在登录页面登录一下，然后复制一个过来这里
wrk.headers["Authorization"]="Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjIzODYzOTIsIlVpZCI6MSwiU3NpZCI6ImE4YmRlOGQxLTkzYjAtNDJmOS04MzdkLWRkYTQ0ZTA4OTQwMiIsIlVzZXJBZ2VudCI6Ik1vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjYuMC4wLjAgU2FmYXJpLzUzNy4zNiJ9.47aT2qABQQ2YwWOJ8LsRBO5Add1hSfkwcoLU3ryDFRCfWHNyfHPY8SlVTP63iBLlmiHS4i-yktVm6U92UlQc0Q"