// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirev1

import (
	"gitee.com/geekbang/basic-go/wirev1/repository"
	"gitee.com/geekbang/basic-go/wirev1/repository/dao"
)

// Injectors from wire.go:

func InitUserRepository() *repository.UserRepository {
	db := InitDB()
	userDAO := dao.NewUserDAO(db)
	userRepository := repository.NewUserRespository(userDAO)
	return userRepository
}
